version: '3.1'

services:

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DB_NAME:-app}"
      MYSQL_USER: "${DB_USER:-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - 3306:3306

  ###< doctrine/doctrine-bundle ###
  phpmyadmin:

    image: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: "${DB_USER:-user}"
      PMA_PASSWORD: "${DB_PASSWORD:-password}"
    depends_on:
      - database
    ports:
      - ${PORT_PHPMYADMIN:-8080}:80

